USE [master]
GO

CREATE DATABASE [IT488]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IT488', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IT488.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IT488_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IT488_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IT488].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IT488] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IT488] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IT488] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IT488] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IT488] SET ARITHABORT OFF 
GO

ALTER DATABASE [IT488] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IT488] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IT488] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IT488] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IT488] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IT488] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IT488] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IT488] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IT488] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IT488] SET  ENABLE_BROKER 
GO

ALTER DATABASE [IT488] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IT488] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IT488] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IT488] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IT488] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IT488] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IT488] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IT488] SET RECOVERY FULL 
GO

ALTER DATABASE [IT488] SET  MULTI_USER 
GO

ALTER DATABASE [IT488] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IT488] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IT488] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IT488] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IT488] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IT488] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [IT488] SET QUERY_STORE = OFF
GO

ALTER DATABASE [IT488] SET  READ_WRITE 
GO

